name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger when code is pushed to main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stage 1: Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Stage 2: Set up JDK (for Maven build)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Stage 3: Build with Maven
      - name: Build project
        run: |
          mvn clean
          mvn package

      # Stage 4: Build Docker Image
      - name: Build Docker image
        run: docker build -t myfile .

      # Stage 5: Run Docker Container
      - name: Run Docker container
        run: docker run -dt --name appcontainer -p 5081:8080 myfile
